force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <description>to store bus records</description>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Air_Conditioning__c.field-meta.xml
<CustomField>
    <fullName>Air_Conditioning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Air Conditioning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Status__c</fullName>
    <label>Current Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled for maintenance</fullName>
            </value>
            <value>
                <fullName>Undergoing repairs</fullName>
            </value>
            <value>
                <fullName>Ready for use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus__c/fields/ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>ImageUrl__c</fullName>
    <label>ImageUrl</label>
    <length>154</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FleetManagementController.cls
public with sharing class FleetManagementController {

    @AuraEnabled(cacheable = true)
    public static List < Bus__c > getBusList() {
        return [SELECT Id, Name, ImageUrl__c, Year__c, Maximum_Capacity__c, Odometer_Reading__c, Air_Conditioning__c, Current_Status__c
                FROM Bus__c WITH SECURITY_ENFORCED];
    }

    @AuraEnabled
    public static void updateBus(String busId, Map<String, Object> busData) {
        // Convert the received data to a Bus__c sObject
        Bus__c busToUpdate = new Bus__c(Id = busId);
        busToUpdate.Name = (String)busData.get('Name');
        busToUpdate.Odometer_Reading__c = (Decimal)busData.get('Odometer_Reading__c');
    
        // Perform the update
        try {
            update busToUpdate;
            System.debug('new value of Odometer + '+ busToUpdate.Odometer_Reading__c);
        } catch (DmlException e) {
            // Propagate the exception to the client
            throw new AuraHandledException('Cannot update bus: ' + e.getMessage());
        }
    }
}